apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    app: petclinic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: 596212444151.dkr.ecr.eu-west-3.amazonaws.com/skaffold-petclinic
        ports:
          - containerPort: 8080
